# Generated by Django 4.0.6 on 2022-08-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/distributors'),
        ),
    ]
